### PR TITLE
 Pass the accessory to FakeGatoHistoryService

### PR DESCRIPTION
**Pull request by arouanet**
Hi @NorthernMan54,

Thanks a lot for your work on adding fakegato-history support to homebridge-bme280.

The following small PR fixes the call to `FakeGatoHistoryService` to pass it the accessory rather than one of the services. It also changes the name of accessory field from `name` to `displayName`, as this is the way it is defined in the [`Accessory`](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/Accessory.js#L51) class so this is what `FakeGatoHistoryService` expects.

This has little impact, as the accessory is not used much by fakegato-history — mainly to get the accessory's name for logging purposes, — but it makes a difference in one instance: the accessory's name is used as part of the filename when persisting history to the filesystem, so with e.g. 
```
"name_temperature": "Temperature"
```
in the configuration, the file will currently be called `hostname_Temperature_persist.json`. With the fix in place, the file is called `hostname_BME280_persist.json`, as expected.

### CODE REVIEW

**Comment by NorthernMan54** [comment]
@arouanet Tks, give me a couple of days to look at this.

**Comment by NorthernMan54** [comment]
@arouanet I was looking at this, and the fakegato API expects either a service or an accessory depending on if the device is using the accessory or platform homebridge API.  And as this is an accessory, fakegato expects to be passed a service.

If you want to change the storage filename away from using the service name to something else, can I recommend this approach.  The fakegato API includes the ability to pass the filename as part of the options.

'fileName': params.filename || hostname+"_"+service.accessoryName+fileSuffix

If you could change it back to continue to pass the service, but pass the filename you want as part of the options object that would work.  Also please ensure that the filename passed includes the hostname as well.

**Comment by arouanet** [comment]
Hi @NorthernMan54, that's not what I'm seeing from reading fakegato-history's [documentation](https://github.com/simont77/fakegato-history/blob/master/README.md) and from looking at the [code](https://github.com/simont77/fakegato-history/blob/master/fakegato-history.js#L141). Even the code example shows the accessory being passed, and that's an accessory plugin, not a platform. Am I missing something?

https://github.com/simont77/homebridge-weather-station-extended/blob/master/index.js#L287

No worries if you would rather not merge this change, though. Just let me know.

**Comment by NorthernMan54** [comment]
@arouanet If you look back thru the commits for fakegato-history, you will see that I added the code around it's support for the Platform API.  And when we added that the logic in fakegato was adjusted based on the premise that the passed object was either a service or an accessory based on the homebridge API's.

In the code example you shared, that predates that change, and they had mimicked the structure of a service, in particular around displayName which you where playing with.  

See this
https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/Service.js#L40

And this
https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/Accessory.js#L51

I'm okay with accepting a pull request, but the way you approached it isn't in alignment with the vision.  Hence my ask to just use the options object to adjust the filename as you are attempting.

Tks

**Comment by arouanet** [comment]
No worries, I understand. I can't see anything in fakegato-history's documentation or code examples that reflects this change in the passed object being either an accessory or a service, which makes it a bit confusing to say the least. I'm not familiar with the Platform API part of HAP/Homebridge, but I can imagine why there would be required added complexity to support it properly in fakegato.

I don't really like the idea of fixing the filename after the fact because the default one doesn't quite make sense though, it seems pretty hackish to me. I guess what prompted this PR is that I didn't understand why the history service was attached to just the temperature service whereas it processed info pertaining to all weather data (temperature, humidity, pressure). Maybe a proper fix would be to have a single service with three characteristics for the BME280 rather than two separate services for temperature and humidity, but that's probably beyond the scope of this PR, and — I'm guessing? — makes it harder to support both the Home and the Eve apps.

This is getting quite complicated for what I thought was a simple change. It's probably best to leave it as is and close the PR I think!

Cheers,

**Comment by NorthernMan54** [comment]
I agree that the file name is a bit hackish, as when I look at my google drive account I see the data from all my sensors ( 13 of them ) and each is a bit different.  Same are reasonable ie living_room and the others make no sense.  I think I have 4 called temperature and a bunch of just the nodemcu name ie NODE-18A6B3.  But as I never look at them, so it never came up as an issue.  For me this issue was never big enough to worry about.  My only concern was the overwriting of data from running test versions etc, hence the hostname.

For the design you are suggesting, that is exactly how it behaves with the Platform API.  It is a single service aligned to a particular accessory.

If you want to submit a pull request to merge the temperature and humidity into a single icon/accessory as a configurable option, I’m okay with that.

**Comment by arouanet** [comment]
Sounds good. I will close this pull request for now and open another one when I have time to work on streamlining the temperature and humidity services.

**Pull request closed without merging**
